# Generated by Django 4.1.7 on 2023-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_article_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="popular",
            field=models.BooleanField(default=False),
        ),
    ]
